version: "3.4"

services:
  app:
    image: covid-vue:v1
    build:
      context: ''
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "5000:8080"
    restart: unless-stopped