version: '3.3'


services:
  nginx:
    image: nginx:1.15.12
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
#      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www

  web:
    container_name: web
    build:
      context: ""
      dockerfile: web/Dockerfile
    restart: always
    tty: true
    environment:
      SERVICE_NAME: web
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./../:/var/www


  database:
    image: mysql
    container_name: mysql
    restart: always
    tty: true
    build:
      context: mysql
      dockerfile: mysql/Dockerfile
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf

    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=123@123a
      - MYSQL_DATABASE=fabbi_test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123@123a

